# Generated by Django 4.1.2 on 2022-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_membership_address_membership_birtdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='disability_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='gym_information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='program',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
