# Generated by Django 4.1.2 on 2022-10-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_birtdate_membership_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='place_of_birth',
            new_name='birthplace',
        ),
    ]
