# Generated by Django 4.1.2 on 2022-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_membership_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member_class',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
