# Generated by Django 4.1.2 on 2022-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_membership_member_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
