# Generated by Django 4.1.2 on 2022-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_membership_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
