# Generated by Django 4.1.2 on 2023-01-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_membership_end_membership_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
