# Generated by Django 4.1.2 on 2023-01-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_membership_member_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipDetail',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_class',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
