# Generated by Django 4.1.2 on 2023-01-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_membershipdetail_alter_membership_member_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField()),
                ('gross_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.payment'),
        ),
    ]
