# Generated by Django 4.1.2 on 2023-01-28 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_membershipdetail_options_instructor_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat')], default='senin', max_length=6),
        ),
    ]
