# Generated by Django 4.1.2 on 2023-01-28 14:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_instructor_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('senin jam 8', 'Senin Jam 8'), ('senin jam 11', 'Senin Jam 11'), ('senin jam 14', 'Senin Jam 14'), ('senin jam 17', 'Senin Jam 17'), ('selasa jam 8', 'Selasa Jam 8'), ('selasa jam 11', 'Selasa Jam 11'), ('selasa jam 14', 'Selasa Jam 14'), ('selasa jam 17', 'Selasa Jam 17'), ('rabu jam 8', 'Rabu Jam 8'), ('rabu jam 11', 'Rabu Jam 11'), ('rabu jam 14', 'Rabu Jam 14'), ('rabu jam 17', 'Rabu Jam 17')], default='senin jam 8', max_length=250),
        ),
    ]
